In [1]:
"""
1. Carregar
2. Tratar valores nulos "disfarçados"
3. Limpar texto (espaços, maiúsculas/minúsculas)
4. Corrigir encoding
5. Corrigir colunas numéricas sujas de posse de bola e precisao de passes.
6. Tratar outliers
7. Remover duplicatas
8. Reordenar colunas e ordenar linhas
9. Salvar
"""

'\n1. Carregar\n2. Tratar valores nulos "disfarçados"\n3. Limpar texto (espaços, maiúsculas/minúsculas)\n4. Corrigir encoding\n5. Corrigir colunas numéricas sujas de posse de bola e precisao de passes.\n6. Tratar outliers\n7. Remover duplicatas\n8. Reordenar colunas e ordenar linhas\n9. Salvar\n'

In [2]:
#carregamento de dados brutos e bagunçados
import pandas as pd
import numpy as np 

df = pd.read_csv(r"D:\projetos git\analise-de-times-br\data\raw\campeonato-brasileiro-estatisticas-full.csv")
display(df)

,Unnamed: 0,index,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,precisao_passes,passes,escanteios,faltas,impedimentos,cartao_amarelo,cartao_vermelho
0,0,13567,1,1,Guarani,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
1,1,3132,1,1,Vasco,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
2,2,16351,2,1,Athletico-Pr,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
3,3,1191,2,1,Gremio,NaN,0,NaN,NaN,0.0,0,0,0,0.0,0
4,4,5762,3,1,Coritiba,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18325,18325,5309,9163,38,Fortaleza,10.0,5,29.0,NaN,199.0,2,8,3,4.0,0
18326,18326,4973,9164,38,Atletico-Mg,19.0,5,58.0,NaN,614.0,6,11,3,NaN,0
18327,18327,14751,9164,38,Vasco,1.0,0,42.0,92.0,416.0,1,4,0,0.0,1
18328,18328,1774,9165,38,Bragantino,5.0,3,46.0,83.0,283.0,4,15,4,4.0,0
18329,18329,17911,9165,38,Internacional,14.0,4,54.0,83.0,NaN,2,15,3,2.0,0

In [3]:
#limpar dados nulos disfarçados
fake_nulls = ["", " ", "NA", "N/A", "na", "n/a", "null", "NULL", "None", "none"]
df.replace(fake_nulls, np.nan, inplace=True)

,Unnamed: 0,index,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,precisao_passes,passes,escanteios,faltas,impedimentos,cartao_amarelo,cartao_vermelho
0,0,13567,1,1,Guarani,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
1,1,3132,1,1,Vasco,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
2,2,16351,2,1,Athletico-Pr,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
3,3,1191,2,1,Gremio,NaN,0,NaN,NaN,0.0,0,0,0,0.0,0
4,4,5762,3,1,Coritiba,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18325,18325,5309,9163,38,Fortaleza,10.0,5,29.0,NaN,199.0,2,8,3,4.0,0
18326,18326,4973,9164,38,Atletico-Mg,19.0,5,58.0,NaN,614.0,6,11,3,NaN,0
18327,18327,14751,9164,38,Vasco,1.0,0,42.0,92.0,416.0,1,4,0,0.0,1
18328,18328,1774,9165,38,Bragantino,5.0,3,46.0,83.0,283.0,4,15,4,4.0,0
18329,18329,17911,9165,38,Internacional,14.0,4,54.0,83.0,NaN,2,15,3,2.0,0

In [4]:
#limpar texto de maisculas e minusculas e limpar espaços em branco
coluna_clube = df['clube']
for coluna in coluna_clube:
    df["clube"] = df["clube"].str.strip().str.title()

display(df)

,Unnamed: 0,index,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,precisao_passes,passes,escanteios,faltas,impedimentos,cartao_amarelo,cartao_vermelho
0,0,13567,1,1,Guarani,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
1,1,3132,1,1,Vasco,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
2,2,16351,2,1,Athletico-Pr,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
3,3,1191,2,1,Gremio,NaN,0,NaN,NaN,0.0,0,0,0,0.0,0
4,4,5762,3,1,Coritiba,0.0,0,NaN,NaN,0.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18325,18325,5309,9163,38,Fortaleza,10.0,5,29.0,NaN,199.0,2,8,3,4.0,0
18326,18326,4973,9164,38,Atletico-Mg,19.0,5,58.0,NaN,614.0,6,11,3,NaN,0
18327,18327,14751,9164,38,Vasco,1.0,0,42.0,92.0,416.0,1,4,0,0.0,1
18328,18328,1774,9165,38,Bragantino,5.0,3,46.0,83.0,283.0,4,15,4,4.0,0
18329,18329,17911,9165,38,Internacional,14.0,4,54.0,83.0,NaN,2,15,3,2.0,0

In [5]:
#Correção do encoding do arquivo, o arquivo original esta com enconding incorreto
#Se faz necessário corrigir o encoding para evitar problemas com caracteres especiais
def corrigur_encoding(valor):
    if not isinstance(valor, str):
        return valor
    try:
        return valor.encode('latin1').decode('utf-8')
    except (UnicodeDecodeError, UnicodeEncodeError):
        return valor

for coluna in ['clube']:
    df[coluna] = df[coluna].apply(corrigur_encoding)

In [ ]:
#correção da coluna de posse de de bola, foi retirado o sinal de poprcetagem afim de potencialmente analisar estes dados mais tarde.
for coluna in ['posse_de_bola', "precisao_passes"]:
    if df[coluna].dtype == "object":
        df[coluna] = df[coluna].str.replace("%", "", regex=False)
        df[coluna] = df[coluna].str.replace(" un", "", regex=False)
        df[coluna] = df[coluna].str.replace(",", ".", regex=False)
    df[coluna] = pd.to_numeric(df[coluna], errors="coerce")

 #correção da coluna chutes e passe (so foram transformados para numericos)
for coluna in ["chutes","passes"]:
    df[coluna] = pd.to_numeric(df[coluna], errors="coerce")

df["chutes"] = df["chutes"].astype("Int64")
df["passes"] = df["passes"].astype("Int64") 
df["posse_de_bola"] = df["posse_de_bola"].astype("Int64")
df["precisao_passes"] = df["precisao_passes"].astype("Int64")

In [7]:
#tratamento de outliers
#obs: tive um erro na logica do for ja qque inverti os sinais de < e >, agora esta funcionando 
#tanto cartoes veremlhos e amarelos nao podem ser negativos e alem disso tirei a casa decimal dos dois
for coluna in ["posse_de_bola","precisao_passes"]:
    fora_do_intervalo = (df[coluna] < 0) | (df[coluna] > 100)
    df.loc[fora_do_intervalo, coluna] = np.nan

cartao_amarelo_negativo = df["cartao_amarelo"] < 0 
df.loc[cartao_amarelo_negativo, "cartao_amarelo"] = np.nan  

cartao_vermelho_negativo = df["cartao_vermelho"] < 0 
df.loc[cartao_vermelho_negativo, "cartao_vermelho"] = np.nan  


df["cartao_amarelo"] = df["cartao_amarelo"].astype("Int64")
df["cartao_vermelho"] = df["cartao_vermelho"].astype("Int64")

In [8]:
#removendo duplicatas
chave_unica = ["partida_id", "clube"]
duplicatas = df.duplicated(subset=chave_unica).sum()
df = df.drop_duplicates(subset=chave_unica, keep='first')
display(df)

,Unnamed: 0,index,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,precisao_passes,passes,escanteios,faltas,impedimentos,cartao_amarelo,cartao_vermelho
0,0,13567,1,1,Guarani,0,0,NaN,NaN,0,0,0,0,0,0
1,1,3132,1,1,Vasco,0,0,NaN,NaN,0,0,0,0,0,0
2,2,16351,2,1,Athletico-Pr,0,0,NaN,NaN,0,0,0,0,0,0
3,3,1191,2,1,Gremio,<NA>,0,NaN,NaN,0,0,0,0,0,0
4,4,5762,3,1,Coritiba,0,0,NaN,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18325,18325,5309,9163,38,Fortaleza,10,5,29.0,NaN,199,2,8,3,4,0
18326,18326,4973,9164,38,Atletico-Mg,19,5,58.0,NaN,614,6,11,3,<NA>,0
18327,18327,14751,9164,38,Vasco,1,0,42.0,92.0,416,1,4,0,0,1
18328,18328,1774,9165,38,Bragantino,5,3,46.0,83.0,283,4,15,4,4,0
18329,18329,17911,9165,38,Internacional,14,4,54.0,83.0,<NA>,2,15,3,2,0

In [9]:
#ordenação da tabela de acordo com o id da partida e clube
ordem_das_colunas = [
    "partida_id", "rodata", "clube",
    "chutes", "chutes_no_alvo", "posse_de_bola", "precisao_passes", "passes",
    "escanteios", "faltas", "impedimentos",
    "cartao_amarelo", "cartao_vermelho",
]
df = df[ordem_das_colunas]
df = df.sort_values(["partida_id", "clube"]).reset_index(drop=True)
display(df)

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,precisao_passes,passes,escanteios,faltas,impedimentos,cartao_amarelo,cartao_vermelho
0,1,1,Guarani,0,0,NaN,NaN,0,0,0,0,0,0
1,1,1,Vasco,0,0,NaN,NaN,0,0,0,0,0,0
2,2,1,Athletico-Pr,0,0,NaN,NaN,0,0,0,0,0,0
3,2,1,Gremio,<NA>,0,NaN,NaN,0,0,0,0,0,0
4,3,1,Coritiba,0,0,NaN,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18325,9163,38,Fortaleza,10,5,29.0,NaN,199,2,8,3,4,0
18326,9164,38,Atletico-Mg,19,5,58.0,NaN,614,6,11,3,<NA>,0
18327,9164,38,Vasco,1,0,42.0,92.0,416,1,4,0,0,1
18328,9165,38,Bragantino,5,3,46.0,83.0,283,4,15,4,4,0
18329,9165,38,Internacional,14,4,54.0,83.0,<NA>,2,15,3,2,0

In [10]:
#salvar no caminho indicado
print("\n" + "=" * 60)
print("RELATÓRIO DE COBERTURA DE DADOS")
print("=" * 60)
 
colunas_para_checar = ["posse_de_bola", "precisao_passes", "chutes", "passes"]
 
for coluna in colunas_para_checar:
    total_preenchido = df[coluna].notna().sum()
    percentual_cobertura = (total_preenchido / len(df)) * 100
 
    # partida_id mínimo entre as linhas ONDE essa coluna tem dado
    linhas_com_dado = df[df[coluna].notna()]
    if len(linhas_com_dado) > 0:
        primeiro_id_com_dado = linhas_com_dado["partida_id"].min()
    else:
        primeiro_id_com_dado = "nenhum dado disponível"
 
    print(f"\n{coluna}:")
    print(f"  Cobertura: {total_preenchido}/{len(df)} linhas ({percentual_cobertura:.1f}%)")
    print(f"  Primeiro partida_id com dado preenchido: {primeiro_id_com_dado}")
 
print("\n" + "=" * 60)


caminho = r"D:\projetos git\analise-de-times-br\data\processed\campeonato-brasileiro-estatisticas-limpo.csv"
df.to_csv(caminho, index=False)

============================================================
RELATÓRIO DE COBERTURA DE DADOS
============================================================

posse_de_bola:
  Cobertura: 7016/18330 linhas (38.3%)
  Primeiro partida_id com dado preenchido: 4698

precisao_passes:
  Cobertura: 4887/18330 linhas (26.7%)
  Primeiro partida_id com dado preenchido: 6126

chutes:
  Cobertura: 16956/18330 linhas (92.5%)
  Primeiro partida_id com dado preenchido: 1

passes:
  Cobertura: 16956/18330 linhas (92.5%)
  Primeiro partida_id com dado preenchido: 1

============================================================